language: node_js
branches:
  only:
  - master
  - dev
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
  yarn: true
script:
  - yarn
  - yarn lint
  - yarn build
notifications:
  slack: uttnetgroup:wIIt6boEZlbKTo6dxPCpm8Ke
  webhooks:
    urls:
      - $OSO_WEBHOOK
    on_success: always
    on_failure: never
    on_start:   never
    on_cancel:  never
    on_error:   never